USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS OLIST;
CREATE SCHEMA IF NOT EXISTS OLIST.RAW;
CREATE SCHEMA IF NOT EXISTS OLIST.SILVER;
CREATE SCHEMA IF NOT EXISTS OLIST.GOLD;
CREATE SCHEMA IF NOT EXISTS OLIST.GOVERNANCE COMMENT='Governance objects for Olist Analytics';
