USE ROLE SYSADMIN;
CREATE WAREHOUSE IF NOT EXISTS OLIST_BI_WH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE INITIALLY_SUSPENDED=TRUE COMMENT='Warehouse dedicated to Power BI workloads for Olist Analytics';
CREATE WAREHOUSE IF NOT EXISTS OLIST_ANALYTICS_WH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE INITIALLY_SUSPENDED=TRUE COMMENT='Warehouse dedicated to analyst workloads for Olist Analytics';
SHOW WAREHOUSES LIKE 'OLIST%';
