USE ROLE ACCOUNTADMIN;
CREATE RESOURCE MONITOR IF NOT EXISTS OLIST_RESOURCE_MONITOR WITH CREDIT_QUOTA=10 FREQUENCY=MONTHLY START_TIMESTAMP=IMMEDIATELY
TRIGGERS ON 50 PERCENT DO NOTIFY ON 75 PERCENT DO NOTIFY ON 90 PERCENT DO NOTIFY ON 100 PERCENT DO SUSPEND;
ALTER WAREHOUSE OLIST_BI_WH SET RESOURCE_MONITOR=OLIST_RESOURCE_MONITOR;
ALTER WAREHOUSE OLIST_ANALYTICS_WH SET RESOURCE_MONITOR=OLIST_RESOURCE_MONITOR;
SHOW RESOURCE MONITORS;
