WITH ORDERS AS (

    SELECT *
    FROM {{ ref('stg_orders') }}

),

ITEMS_AGG AS (

    SELECT
        ORDER_ID,
        COUNT(*) AS ITEM_COUNT,
        SUM(PRICE) AS TOTAL_PRODUCT_VALUE,
        SUM(FREIGHT_VALUE) AS TOTAL_FREIGHT_VALUE,
        SUM(PRICE + FREIGHT_VALUE) AS TOTAL_ORDER_VALUE

    FROM {{ ref('stg_order_items') }}

    GROUP BY ORDER_ID

),

PAYMENTS_AGG AS (

    SELECT
        ORDER_ID,
        COUNT(*) AS PAYMENT_COUNT,
        SUM(PAYMENT_VALUE) AS TOTAL_PAYMENT_VALUE

    FROM {{ ref('stg_payments') }}

    GROUP BY ORDER_ID

)

SELECT
    O.ORDER_ID,
    O.CUSTOMER_ID,
    O.ORDER_STATUS,
    O.ORDER_PURCHASE_TIMESTAMP,
    O.ORDER_APPROVED_AT,
    O.ORDER_DELIVERED_CARRIER_DATE,
    O.ORDER_DELIVERED_CUSTOMER_DATE,
    O.ORDER_ESTIMATED_DELIVERY_DATE,

    TO_NUMBER(
        TO_CHAR(
            CAST(O.ORDER_PURCHASE_TIMESTAMP AS DATE),
            'YYYYMMDD'
        )
    ) AS PURCHASE_DATE_KEY,

    DATEDIFF(
        DAY,
        O.ORDER_PURCHASE_TIMESTAMP,
        O.ORDER_DELIVERED_CUSTOMER_DATE
    ) AS DELIVERY_DAYS,

    DATEDIFF(
        DAY,
        O.ORDER_ESTIMATED_DELIVERY_DATE,
        O.ORDER_DELIVERED_CUSTOMER_DATE
    ) AS DELAY_DAYS,

    CASE
        WHEN O.ORDER_DELIVERED_CUSTOMER_DATE >
             O.ORDER_ESTIMATED_DELIVERY_DATE
        THEN TRUE
        ELSE FALSE
    END AS IS_LATE_DELIVERY,

    COALESCE(I.ITEM_COUNT, 0) AS ITEM_COUNT,
    COALESCE(I.TOTAL_PRODUCT_VALUE, 0) AS TOTAL_PRODUCT_VALUE,
    COALESCE(I.TOTAL_FREIGHT_VALUE, 0) AS TOTAL_FREIGHT_VALUE,
    COALESCE(I.TOTAL_ORDER_VALUE, 0) AS TOTAL_ORDER_VALUE,
    COALESCE(P.PAYMENT_COUNT, 0) AS PAYMENT_COUNT,
    COALESCE(P.TOTAL_PAYMENT_VALUE, 0) AS TOTAL_PAYMENT_VALUE

FROM ORDERS O

LEFT JOIN ITEMS_AGG I
    ON O.ORDER_ID = I.ORDER_ID

LEFT JOIN PAYMENTS_AGG P
    ON O.ORDER_ID = P.ORDER_ID