WITH REVIEWS AS (

    SELECT * FROM {{ ref('stg_reviews') }}

)

SELECT
    REVIEW_ID,
    ORDER_ID,
    REVIEW_SCORE,
    REVIEW_COMMENT_TITLE,
    REVIEW_COMMENT_MESSAGE,
    REVIEW_CREATION_DATE,
    REVIEW_ANSWER_TIMESTAMP,

    TO_NUMBER(
        TO_CHAR(
            CAST(REVIEW_CREATION_DATE AS DATE),
            'YYYYMMDD'
        )
    ) AS REVIEW_DATE_KEY,

    DATEDIFF(
        HOUR,
        REVIEW_CREATION_DATE,
        REVIEW_ANSWER_TIMESTAMP
    ) AS REVIEW_RESPONSE_HOURS,

    CASE
        WHEN REVIEW_COMMENT_MESSAGE IS NOT NULL
        THEN TRUE
        ELSE FALSE
    END AS HAS_COMMENT

FROM REVIEWS