WITH ORDER_ITEMS AS (

    SELECT * FROM {{ ref('stg_order_items') }}

)

SELECT
    ORDER_ID,
    ORDER_ITEM_ID,
    PRODUCT_ID,
    SELLER_ID,
    SHIPPING_LIMIT_DATE,
    PRICE,
    FREIGHT_VALUE,
    PRICE + FREIGHT_VALUE AS ITEM_TOTAL_VALUE

FROM ORDER_ITEMS