-- Silver x Gold reconciliation
SELECT
 (SELECT COUNT(*) FROM OLIST.SILVER.STG_CUSTOMERS) SILVER_CUSTOMERS,
 (SELECT COUNT(*) FROM OLIST.GOLD.DIM_CUSTOMER) GOLD_CUSTOMERS,
 (SELECT COUNT(*) FROM OLIST.SILVER.STG_PRODUCTS) SILVER_PRODUCTS,
 (SELECT COUNT(*) FROM OLIST.GOLD.DIM_PRODUCT) GOLD_PRODUCTS,
 (SELECT COUNT(*) FROM OLIST.SILVER.STG_SELLERS) SILVER_SELLERS,
 (SELECT COUNT(*) FROM OLIST.GOLD.DIM_SELLER) GOLD_SELLERS,
 (SELECT COUNT(*) FROM OLIST.SILVER.STG_ORDERS) SILVER_ORDERS,
 (SELECT COUNT(*) FROM OLIST.GOLD.FCT_ORDERS) GOLD_ORDERS,
 (SELECT COUNT(*) FROM OLIST.SILVER.STG_ORDER_ITEMS) SILVER_ITEMS,
 (SELECT COUNT(*) FROM OLIST.GOLD.FCT_ORDER_ITEMS) GOLD_ITEMS,
 (SELECT COUNT(*) FROM OLIST.SILVER.STG_PAYMENTS) SILVER_PAYMENTS,
 (SELECT COUNT(*) FROM OLIST.GOLD.FCT_PAYMENTS) GOLD_PAYMENTS,
 (SELECT COUNT(*) FROM OLIST.SILVER.STG_REVIEWS) SILVER_REVIEWS,
 (SELECT COUNT(*) FROM OLIST.GOLD.FCT_REVIEWS) GOLD_REVIEWS;

-- Financial reconciliation
SELECT
 ROUND((SELECT SUM(PRICE) FROM OLIST.SILVER.STG_ORDER_ITEMS),2) SILVER_PRODUCT_VALUE,
 ROUND((SELECT SUM(PRICE) FROM OLIST.GOLD.FCT_ORDER_ITEMS),2) GOLD_PRODUCT_VALUE,
 ROUND((SELECT SUM(FREIGHT_VALUE) FROM OLIST.SILVER.STG_ORDER_ITEMS),2) SILVER_FREIGHT,
 ROUND((SELECT SUM(FREIGHT_VALUE) FROM OLIST.GOLD.FCT_ORDER_ITEMS),2) GOLD_FREIGHT,
 ROUND((SELECT SUM(PAYMENT_VALUE) FROM OLIST.SILVER.STG_PAYMENTS),2) SILVER_PAYMENT_VALUE,
 ROUND((SELECT SUM(PAYMENT_VALUE) FROM OLIST.GOLD.FCT_PAYMENTS),2) GOLD_PAYMENT_VALUE;
