with source as (
    select * from {{ source('raw_data', 'PRODUCTS') }}
),

PRODUCTS as (
    SELECT
        PRODUCT_ID::VARCHAR                       AS PRODUCT_ID,
        PRODUCT_CATEGORY_NAME::VARCHAR            AS PRODUCT_CATEGORY_NAME,
        TRY_TO_NUMBER(PRODUCT_NAME_LENGHT)        AS PRODUCT_NAME_LENGTH,
        TRY_TO_NUMBER(PRODUCT_DESCRIPTION_LENGHT) AS PRODUCT_DESCRIPTION_LENGTH,
        TRY_TO_NUMBER(PRODUCT_PHOTOS_QTY)         AS PRODUCT_PHOTOS_QTY,
        TRY_TO_DECIMAL(PRODUCT_WEIGHT_G, 12, 2)   AS PRODUCT_WEIGHT_G,
        TRY_TO_DECIMAL(PRODUCT_LENGTH_CM, 12, 2)  AS PRODUCT_LENGTH_CM,
        TRY_TO_DECIMAL(PRODUCT_HEIGHT_CM, 12, 2)  AS PRODUCT_HEIGHT_CM,
        TRY_TO_DECIMAL(PRODUCT_WIDTH_CM, 12, 2)   AS PRODUCT_WIDTH_CM
    FROM source
)

select * from PRODUCTS