with source as (
    select * from {{ source('raw_data', 'ORDERS') }}
),

ORDERS as (
    SELECT
        ORDER_ID::VARCHAR                                   AS ORDER_ID,
        CUSTOMER_ID::VARCHAR                                AS CUSTOMER_ID,
        LOWER(TRIM(ORDER_STATUS))::VARCHAR                  AS ORDER_STATUS,
        TRY_TO_TIMESTAMP_NTZ(ORDER_PURCHASE_TIMESTAMP)      AS ORDER_PURCHASE_TIMESTAMP,
        TRY_TO_TIMESTAMP_NTZ(ORDER_APPROVED_AT)             AS ORDER_APPROVED_AT,
        TRY_TO_TIMESTAMP_NTZ(ORDER_DELIVERED_CARRIER_DATE)  AS ORDER_DELIVERED_CARRIER_DATE,
        TRY_TO_TIMESTAMP_NTZ(ORDER_DELIVERED_CUSTOMER_DATE) AS ORDER_DELIVERED_CUSTOMER_DATE,
        TRY_TO_TIMESTAMP_NTZ(ORDER_ESTIMATED_DELIVERY_DATE) AS ORDER_ESTIMATED_DELIVERY_DATE
    FROM source
)

select * from ORDERS