-- Run only against this disposable lab table.
USE ROLE OLIST_DATA_ENGINEER;
CREATE OR REPLACE TRANSIENT TABLE OLIST.GOLD.FCT_ORDERS_TIMETRAVEL_LAB CLONE OLIST.GOLD.FCT_ORDERS;
SELECT CURRENT_TIMESTAMP() AS BEFORE_DELETE;
DELETE FROM OLIST.GOLD.FCT_ORDERS_TIMETRAVEL_LAB WHERE ORDER_STATUS='delivered';

-- Recovery template: replace timestamp with BEFORE_DELETE value.
-- INSERT INTO OLIST.GOLD.FCT_ORDERS_TIMETRAVEL_LAB
-- SELECT * FROM OLIST.GOLD.FCT_ORDERS_TIMETRAVEL_LAB
-- AT (TIMESTAMP => '<TIMESTAMP_BEFORE_INCIDENT>'::TIMESTAMP_TZ)
-- WHERE ORDER_STATUS='delivered';

SELECT COUNT(*) MISSING_ROWS FROM (
 SELECT * FROM OLIST.GOLD.FCT_ORDERS
 MINUS
 SELECT * FROM OLIST.GOLD.FCT_ORDERS_TIMETRAVEL_LAB
);
