-- RAW layer: JSON is preserved as VARIANT; tabular sources arrive as VARCHAR.
CREATE OR REPLACE TABLE OLIST.RAW.ORDERS (ORDER_ID VARCHAR,CUSTOMER_ID VARCHAR,ORDER_STATUS VARCHAR,ORDER_PURCHASE_TIMESTAMP VARCHAR,ORDER_APPROVED_AT VARCHAR,ORDER_DELIVERED_CARRIER_DATE VARCHAR,ORDER_DELIVERED_CUSTOMER_DATE VARCHAR,ORDER_ESTIMATED_DELIVERY_DATE VARCHAR);
CREATE OR REPLACE TABLE OLIST.RAW.ORDER_ITEMS (ORDER_ID VARCHAR,ORDER_ITEM_ID VARCHAR,PRODUCT_ID VARCHAR,SELLER_ID VARCHAR,SHIPPING_LIMIT_DATE VARCHAR,PRICE VARCHAR,FREIGHT_VALUE VARCHAR);
CREATE OR REPLACE TABLE OLIST.RAW.CUSTOMERS (RAW_CUSTOMERS VARIANT);
CREATE OR REPLACE TABLE OLIST.RAW.PAYMENTS (RAW_PAYMENTS VARIANT);
CREATE OR REPLACE TABLE OLIST.RAW.REVIEWS (RAW_REVIEWS VARIANT);
CREATE OR REPLACE TABLE OLIST.RAW.PRODUCTS (PRODUCT_ID VARCHAR,PRODUCT_CATEGORY_NAME VARCHAR,PRODUCT_NAME_LENGHT VARCHAR,PRODUCT_DESCRIPTION_LENGHT VARCHAR,PRODUCT_PHOTOS_QTY VARCHAR,PRODUCT_WEIGHT_G VARCHAR,PRODUCT_LENGTH_CM VARCHAR,PRODUCT_HEIGHT_CM VARCHAR,PRODUCT_WIDTH_CM VARCHAR);
CREATE OR REPLACE TABLE OLIST.RAW.SELLERS (SELLER_ID VARCHAR,SELLER_ZIP_CODE_PREFIX VARCHAR,SELLER_CITY VARCHAR,SELLER_STATE VARCHAR);
CREATE OR REPLACE TABLE OLIST.RAW.GEOLOCATION (GEOLOCATION_ZIP_CODE_PREFIX VARCHAR,GEOLOCATION_LAT VARCHAR,GEOLOCATION_LNG VARCHAR,GEOLOCATION_CITY VARCHAR,GEOLOCATION_STATE VARCHAR);
CREATE OR REPLACE TABLE OLIST.RAW.CATEGORY_TRANSLATION (PRODUCT_CATEGORY_NAME VARCHAR,PRODUCT_CATEGORY_NAME_ENGLISH VARCHAR);
