WITH DATE_BOUNDS AS (

    SELECT
        MIN(CAST(ORDER_PURCHASE_TIMESTAMP AS DATE)) AS MIN_DATE,
        MAX(CAST(ORDER_PURCHASE_TIMESTAMP AS DATE)) AS MAX_DATE
    FROM {{ ref('stg_orders') }}

),

DATE_SPINE AS (

    SELECT
        DATEADD(DAY,SEQ4(),MIN_DATE) AS FULL_DATE,
        MAX_DATE
    FROM DATE_BOUNDS,
         TABLE(
             GENERATOR(
                 ROWCOUNT => 5000
             )
         )

),

FILTERED_DATES AS (

    SELECT
        FULL_DATE
    FROM DATE_SPINE
    WHERE FULL_DATE <= MAX_DATE

)

SELECT
    TO_NUMBER(TO_CHAR(FULL_DATE, 'YYYYMMDD')) AS DATE_KEY,
    FULL_DATE,
    YEAR(FULL_DATE) AS YEAR,
    QUARTER(FULL_DATE) AS QUARTER,
    MONTH(FULL_DATE) AS MONTH,
    MONTHNAME(FULL_DATE) AS MONTH_NAME,
    DAY(FULL_DATE) AS DAY,
    DAYOFWEEKISO(FULL_DATE) AS DAY_OF_WEEK,
    DAYNAME(FULL_DATE) AS DAY_NAME,
    WEEKOFYEAR(FULL_DATE) AS WEEK_OF_YEAR,

    CASE
        WHEN DAYOFWEEKISO(FULL_DATE) IN (6, 7)
        THEN TRUE
        ELSE FALSE
    END AS IS_WEEKEND

FROM FILTERED_DATES