WITH SOURCE AS (

    SELECT
        GEOLOCATION_ZIP_CODE_PREFIX,
        GEOLOCATION_CITY,
        GEOLOCATION_STATE,
        GEOLOCATION_LAT,
        GEOLOCATION_LNG
    FROM {{ ref('stg_geolocation') }}

),

-- Quantidade de ocorrências de cada cidade/estado por CEP
LOCALITY_COUNT AS (

    SELECT
        GEOLOCATION_ZIP_CODE_PREFIX,
        GEOLOCATION_CITY,
        GEOLOCATION_STATE,
        COUNT(*) AS LOCALITY_COUNT
    FROM SOURCE

    GROUP BY
        GEOLOCATION_ZIP_CODE_PREFIX,
        GEOLOCATION_CITY,
        GEOLOCATION_STATE

),

-- Define a localidade predominante para cada CEP
LOCALITY_RANK AS (

    SELECT
        GEOLOCATION_ZIP_CODE_PREFIX,
        GEOLOCATION_CITY,
        GEOLOCATION_STATE,
        LOCALITY_COUNT,

        ROW_NUMBER() OVER (
            PARTITION BY GEOLOCATION_ZIP_CODE_PREFIX
            ORDER BY
                LOCALITY_COUNT DESC,
                GEOLOCATION_STATE,
                GEOLOCATION_CITY
        ) AS RN

    FROM LOCALITY_COUNT

),

PRIMARY_LOCALITY AS (

    SELECT
        GEOLOCATION_ZIP_CODE_PREFIX,
        GEOLOCATION_CITY,
        GEOLOCATION_STATE
    FROM LOCALITY_RANK
    WHERE RN = 1

),

-- Consolida as coordenadas por prefixo de CEP
COORDINATES AS (

    SELECT
        GEOLOCATION_ZIP_CODE_PREFIX,

        AVG(GEOLOCATION_LAT) AS GEOLOCATION_LAT,
        AVG(GEOLOCATION_LNG) AS GEOLOCATION_LNG,

        COUNT(*) AS SOURCE_RECORD_COUNT

    FROM SOURCE

    GROUP BY GEOLOCATION_ZIP_CODE_PREFIX

)

SELECT
    C.GEOLOCATION_ZIP_CODE_PREFIX,
    L.GEOLOCATION_CITY,
    L.GEOLOCATION_STATE,

    C.GEOLOCATION_LAT,
    C.GEOLOCATION_LNG,

    C.SOURCE_RECORD_COUNT

FROM COORDINATES C

LEFT JOIN PRIMARY_LOCALITY L
    ON C.GEOLOCATION_ZIP_CODE_PREFIX =
       L.GEOLOCATION_ZIP_CODE_PREFIX