WITH PRODUCTS AS (

    SELECT *
    FROM {{ ref('stg_products') }}

),

CATEGORY_TRANSLATION AS (

    SELECT *
    FROM {{ ref('stg_category_translation') }}

)

SELECT
    P.PRODUCT_ID,
    P.PRODUCT_CATEGORY_NAME,
    C.PRODUCT_CATEGORY_NAME_ENGLISH,
    P.PRODUCT_NAME_LENGTH,
    P.PRODUCT_DESCRIPTION_LENGTH,
    P.PRODUCT_PHOTOS_QTY,
    P.PRODUCT_WEIGHT_G,
    P.PRODUCT_LENGTH_CM,
    P.PRODUCT_HEIGHT_CM,
    P.PRODUCT_WIDTH_CM
FROM PRODUCTS P

LEFT JOIN CATEGORY_TRANSLATION C
    ON P.PRODUCT_CATEGORY_NAME = C.PRODUCT_CATEGORY_NAME