USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS OLIST_DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS OLIST_DATA_ANALYST;
CREATE ROLE IF NOT EXISTS OLIST_BI;
CREATE ROLE IF NOT EXISTS OLIST_ANALYST_SP;
CREATE ROLE IF NOT EXISTS OLIST_ANALYST_RJ;

GRANT USAGE ON DATABASE OLIST TO ROLE OLIST_DATA_ANALYST;
GRANT USAGE ON SCHEMA OLIST.GOLD TO ROLE OLIST_DATA_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA OLIST.GOLD TO ROLE OLIST_DATA_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA OLIST.GOLD TO ROLE OLIST_DATA_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA OLIST.GOLD TO ROLE OLIST_DATA_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA OLIST.GOLD TO ROLE OLIST_DATA_ANALYST;
GRANT USAGE ON WAREHOUSE OLIST_ANALYTICS_WH TO ROLE OLIST_DATA_ANALYST;

GRANT USAGE ON DATABASE OLIST TO ROLE OLIST_BI;
GRANT USAGE ON SCHEMA OLIST.GOLD TO ROLE OLIST_BI;
GRANT SELECT ON ALL TABLES IN SCHEMA OLIST.GOLD TO ROLE OLIST_BI;
GRANT SELECT ON FUTURE TABLES IN SCHEMA OLIST.GOLD TO ROLE OLIST_BI;
GRANT USAGE ON WAREHOUSE OLIST_BI_WH TO ROLE OLIST_BI;

GRANT USAGE ON DATABASE OLIST TO ROLE OLIST_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE OLIST_DATA_ENGINEER;
GRANT USAGE ON SCHEMA OLIST.RAW TO ROLE OLIST_DATA_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA OLIST.RAW TO ROLE OLIST_DATA_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA OLIST.RAW TO ROLE OLIST_DATA_ENGINEER;
GRANT USAGE ON SCHEMA OLIST.SILVER TO ROLE OLIST_DATA_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA OLIST.SILVER TO ROLE OLIST_DATA_ENGINEER;
GRANT SELECT ON ALL VIEWS IN SCHEMA OLIST.SILVER TO ROLE OLIST_DATA_ENGINEER;
GRANT CREATE TABLE ON SCHEMA OLIST.SILVER TO ROLE OLIST_DATA_ENGINEER;
GRANT CREATE VIEW ON SCHEMA OLIST.SILVER TO ROLE OLIST_DATA_ENGINEER;
GRANT USAGE ON SCHEMA OLIST.GOLD TO ROLE OLIST_DATA_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA OLIST.GOLD TO ROLE OLIST_DATA_ENGINEER;
GRANT SELECT ON ALL VIEWS IN SCHEMA OLIST.GOLD TO ROLE OLIST_DATA_ENGINEER;
GRANT CREATE TABLE ON SCHEMA OLIST.GOLD TO ROLE OLIST_DATA_ENGINEER;
GRANT CREATE VIEW ON SCHEMA OLIST.GOLD TO ROLE OLIST_DATA_ENGINEER;

GRANT USAGE ON WAREHOUSE OLIST_ANALYTICS_WH TO ROLE OLIST_ANALYST_SP;
GRANT USAGE ON WAREHOUSE OLIST_ANALYTICS_WH TO ROLE OLIST_ANALYST_RJ;
GRANT USAGE ON DATABASE OLIST TO ROLE OLIST_ANALYST_SP;
GRANT USAGE ON DATABASE OLIST TO ROLE OLIST_ANALYST_RJ;
GRANT USAGE ON SCHEMA OLIST.GOLD TO ROLE OLIST_ANALYST_SP;
GRANT USAGE ON SCHEMA OLIST.GOLD TO ROLE OLIST_ANALYST_RJ;
GRANT SELECT ON ALL TABLES IN SCHEMA OLIST.GOLD TO ROLE OLIST_ANALYST_SP;
GRANT SELECT ON ALL TABLES IN SCHEMA OLIST.GOLD TO ROLE OLIST_ANALYST_RJ;

-- User-specific role assignments are intentionally omitted from the public repository.
