USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE MASKING POLICY OLIST.GOVERNANCE.MASK_CUSTOMER_UNIQUE_ID AS (VAL STRING) RETURNS STRING ->
CASE WHEN CURRENT_ROLE()='OLIST_DATA_ENGINEER' THEN VAL ELSE '********************************' END
COMMENT='Masks customer unique identifier for unauthorized roles';
ALTER TABLE OLIST.GOLD.DIM_CUSTOMER MODIFY COLUMN CUSTOMER_UNIQUE_ID SET MASKING POLICY OLIST.GOVERNANCE.MASK_CUSTOMER_UNIQUE_ID;
DESC MASKING POLICY OLIST.GOVERNANCE.MASK_CUSTOMER_UNIQUE_ID;
