USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE ROW ACCESS POLICY OLIST.GOVERNANCE.RAP_CUSTOMER_STATE AS (STATE STRING) RETURNS BOOLEAN ->
CASE
 WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','OLIST_DATA_ENGINEER','OLIST_DATA_ANALYST','OLIST_BI') THEN TRUE
 WHEN CURRENT_ROLE()='OLIST_ANALYST_SP' THEN STATE='SP'
 WHEN CURRENT_ROLE()='OLIST_ANALYST_RJ' THEN STATE='RJ'
 ELSE FALSE END;
ALTER TABLE OLIST.GOLD.DIM_CUSTOMER ADD ROW ACCESS POLICY OLIST.GOVERNANCE.RAP_CUSTOMER_STATE ON (CUSTOMER_STATE);
