USE ROLE ACCOUNTADMIN;
CREATE TAG IF NOT EXISTS OLIST.GOVERNANCE.DATA_SENSITIVITY ALLOWED_VALUES 'PUBLIC','SENSITIVE' COMMENT='Data sensitivity classification for Olist Analytics';
ALTER TABLE OLIST.GOLD.DIM_CUSTOMER MODIFY COLUMN CUSTOMER_UNIQUE_ID SET TAG OLIST.GOVERNANCE.DATA_SENSITIVITY='SENSITIVE';
